import type { Metadata } from "next";
import "@/app/globals.css";
import { Caprasimo, Raleway, Sacramento } from "next/font/google";

export const metadata: Metadata = {
  title: "Oh My Book Events",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-oh-my-book.png",
  },
};

const caprasimo = Caprasimo({
  variable: "--font-caprasimo",
  weight: "400",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  weight: ["500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

const sacramento = Sacramento({
  variable: "--font-sacramento",
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${sacramento.variable} ${caprasimo.variable} ${raleway.className} antialiased`}
      >
        <>{children}</>
      </body>
    </html>
  );
}
