import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Caprasimo, Raleway } from "next/font/google";
import MarkerShapeFilter from "@/components/MarkerShapeFilter";

const caprasimo = Caprasimo({
  variable: "--font-caprasimo",
  weight: "400",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  weight: ["600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Oh My Book Events",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-oh-my-book.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${caprasimo.variable} ${raleway.className} antialiased`}
      >
        <MarkerShapeFilter />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
